name: Plugins CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  galaxy-importer:
    name: "Run galaxy-importer with ansible-test enabled"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: ansible_collections/community/clickhouse

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Galaxy Importer Action
        uses: ./.github/actions/run-galaxy-importer
